name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

      - name: Deploy remoto (escribe archivos y levanta)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            # Instalar Docker si falta
            docker --version || curl -fsSL https://get.docker.com | sh

            # Asegurar "docker compose" o "docker-compose"
            if docker compose version >/dev/null 2>&1; then
              COMPOSE="docker compose"
            else
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
              COMPOSE="docker-compose"
            fi

            # Crear red externa si no existe
            docker network create infra_infra_network || true

            # Carpeta de deploy
            mkdir -p ${{ secrets.SERVER_PATH }}
            cd ${{ secrets.SERVER_PATH }}

            # docker-compose.yml (solo app, sin Caddy)
            cat > docker-compose.yml <<COMPOSE_EOF
            services:
              app:
                image: grupolafecartagena:latest
                container_name: grupo-la-fe-app
                env_file: .env
                restart: unless-stopped
                networks:
                  - infra_infra_network

            networks:
              infra_infra_network:
                external: true
            COMPOSE_EOF

            # .env (runtime) - interpolar secrets aquí
            cat > .env <<ENV_EOF
            CONTACT_TO=${{ secrets.CONTACT_TO }}
            CONTACT_FROM=${{ secrets.CONTACT_FROM }}
            ENV_EOF

            # Levantar contenedores
            \$COMPOSE up -d --remove-orphans

            echo "Deployment completed successfully"