name: deploy
on:
  workflow_run:
    workflows: [ "docker-publish" ]
    types: [ completed ]
    branches: [ main ]

permissions:
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: SSH into droplet and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script_stop: true
          envs: GHCR_USER,GHCR_PAT,SERVER_PATH
          script: |
            set -euxo pipefail

            # defaults
            : "${SERVER_PATH:=/opt/grupo-la-fe}"

            # Docker / Compose
            if ! command -v docker >/dev/null 2>&1; then
              curl -fsSL https://get.docker.com | sh
            fi
            if docker compose version >/dev/null 2>&1; then
              COMPOSE="docker compose"
            else
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
              COMPOSE="docker-compose"
            fi

            # Red externa para hablar con Caddy central
            docker network inspect infra_infra_network >/dev/null 2>&1 || docker network create infra_infra_network

            mkdir -p "$SERVER_PATH"
            cd "$SERVER_PATH"

            # Login a GHCR si la imagen es privada (PAT con 'read:packages')
            if [ -n "${GHCR_PAT:-}" ]; then
              echo "$GHCR_PAT" | docker login ghcr.io -u "${GHCR_USER:-${USER}}" --password-stdin
            fi

            # Copiar docker-compose.prod.yml desde el repo (temporal, en producción clonar el repo)
            # Por ahora, crear el archivo con la imagen correcta
            cat > docker-compose.yml <<'COMPOSE_EOF'
            services:
              app:
                image: ghcr.io/steven230500/grupo-la-fe:latest
                container_name: grupo-la-fe-app
                env_file: .env
                restart: unless-stopped
                networks:
                  - infra_infra_network

            networks:
              infra_infra_network:
                external: true
            COMPOSE_EOF

            # .env con valores hardcodeados temporalmente para debug
            cat > .env <<'ENV_EOF'
            CONTACT_TO=contact@grupolafecartagena.org
            CONTACT_FROM=noreply@grupolafecartagena.org
            ENV_EOF

            # Pull & Up
            $COMPOSE pull
            $COMPOSE up -d --remove-orphans

            # Limpieza opcional
            docker image prune -f || true