name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare SSH key file
        run: |
          echo "${{ secrets.SSH_KEY_B64 }}" | base64 -d > id_ed25519
          chmod 600 id_ed25519

      - name: Deploy remoto (escribe archivos y levanta)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key_path: id_ed25519
          script: |
            set -e

            echo "=== DEBUG: Variables ==="
            echo "SSH_HOST: $SSH_HOST"
            echo "SSH_USER: $SSH_USER"
            echo "SERVER_PATH: $SERVER_PATH"
            echo "========================"

            # Instalar Docker si falta
            docker --version || curl -fsSL https://get.docker.com | sh

            # Asegurar "docker compose" o "docker-compose"
            if docker compose version >/dev/null 2>&1; then
              COMPOSE="docker compose"
            else
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
              COMPOSE="docker-compose"
            fi

            # Carpeta de deploy
            echo "=== DEBUG: Creando directorio ${{ secrets.SERVER_PATH }} ==="
            mkdir -p ${{ secrets.SERVER_PATH }}
            cd ${{ secrets.SERVER_PATH }}
            echo "Directorio actual: $(pwd)"
            echo "Contenido del directorio:"
            ls -la
            echo "=================================="

            # docker-compose.yml (solo app, sin Caddy)
            cat > docker-compose.yml <<'COMPOSE'
            services:
              app:
                image: grupolafecartagena:latest
                container_name: grupo-la-fe-app
                env_file: .env
                restart: unless-stopped
                networks:
                  - infra_infra_network

            networks:
              infra_infra_network:
                external: true
            COMPOSE

            # .env (runtime)
            echo "=== DEBUG: Variables de entorno ==="
            echo "CONTACT_TO: ${{ secrets.CONTACT_TO }}"
            echo "CONTACT_FROM: ${{ secrets.CONTACT_FROM }}"
            echo "=================================="

            cat > .env <<'ENVVARS'
            CONTACT_TO=${{ secrets.CONTACT_TO }}
            CONTACT_FROM=${{ secrets.CONTACT_FROM }}
            ENVVARS

            echo "=== DEBUG: Archivo .env creado ==="
            cat .env
            echo "=================================="

            echo "Starting containers..."
            $COMPOSE up -d --remove-orphans

            echo "=== Archivos ==="; ls -la
            echo "=== Estado ==="; $COMPOSE ps
            echo "=== DEBUG: Finalizado ==="